In [7]:
import numpy as np

# Scalars

In [8]:
j=np.array(14)
print(j.ndim)

0


# Vectors

In [10]:
j=np.array([4,5,2,5,3,4])
print(j.ndim)

1


# Matrices

In [11]:
j=np.array([[4,5],[2,5],[3,4]])
print(j.ndim)

2


# Tensors

In [13]:
j=np.array([
    [[4,5],
    [2,5],
    [3,4],
    ],
    [[4,5],
    [2,5],
    [3,4],
    ]
])
print(j.ndim)

3


In mathematics, a scalar is a single number. A vector is a list of numbers, and a matrix is a rectangular array of numbers. A tensor is a generalization of vectors and matrices to higher dimensions.

Scalars are the simplest type of mathematical object. They are just single numbers. For example, the number 1, the number 2.5, and the number -3 are all scalars.

Vectors are a list of numbers. The numbers in a vector are called the elements of the vector. For example, the vector (1, 2, 3) has three elements: 1, 2, and 3.

Matrices are a rectangular array of numbers. The numbers in a matrix are called the elements of the matrix. For example, the matrix

```
[1 2 3]
[4 5 6]
[7 8 9]
```

has three rows and three columns.

Tensors are a generalization of vectors and matrices to higher dimensions. A tensor with one dimension is a vector. A tensor with two dimensions is a matrix. A tensor with three dimensions is a cube. And so on.

Scalars, vectors, matrices, and tensors are all important mathematical objects. They are used in a wide variety of fields, including physics, chemistry, engineering, and computer science.

Here are some examples of how scalars, vectors, matrices, and tensors are used in machine learning:

* Scalars are used to represent the labels of data points. For example, the label of a data point could be the class of an image.
* Vectors are used to represent the features of data points. For example, the features of an image could be the pixel values.
* Matrices are used to represent the relationships between data points. For example, the matrix of a neural network represents the weights between the neurons.
* Tensors are used to represent the relationships between data points and labels. For example, the tensor of a neural network represents the probability of each data point belonging to each class.

Scalars, vectors, matrices, and tensors are all important mathematical objects that are used in a wide variety of fields, including machine learning.